name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@main
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          envs: DB_URI,AWS_REGION,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY
          script: |
            cd aris-api-gateway
            git pull origin main
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            rm -rf .env
            touch .env
            echo "DB_URI=${{ secrets.DB_URI }}" >> .env
            echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
            nohup python main.py > output.log 2>&1 &
            disown